# 二次元人物声音合成相关设置

# 亚托莉
atri:
  ModulePath: "C:/Users/妖梦/Desktop/TsubakiApi/Api/voice/atri"  # 亚托莉模型的绝对路径
  OutPut: "C:/Users/妖梦/Desktop/TsubakiApi/Api/voice/atri"  # 输出文件的路径 例如 D:/1 不带后缀
  Tacotron: "D:/AtriVoice/Tacotron2Program/inference"  # Tacotron2的路径
  NoisePath: "D:/AtriVoice/Tacotron2Program/inference/denoise" # 降噪文件名

# 柚子社语音合成 所有路径名不允许非英文字符
yuzu:
  ModulePath: "D:/Voice/YuzuVoice/Data/365_epochs.pth" # 柚子社模型的绝对路径 带文件名
  Config: "D:/Voice/YuzuVoice/Data/config.json" # 柚子社设置相关路径 带文件名
  Output: "D:/Voice/YuzuVoice/Data/voice" # 输出路径 不带文件名
  GoeMoePythonPath: "D:/MoeGoe-master/MoeGoe-master" # VGoeMoePython项目文件夹路径
  StringFile: "D:/Voice/YuzuVoice/Data/voice" # 缓存输出文件夹路径 不带文件名


