# 二次元人物声音合成相关设置

# 亚托莉
atri:
  ModulePath: "C:/Users/妖梦/Desktop/TsubakiApi/Api/voice/atri"  # 亚托莉模型的绝对路径
  OutPut: "C:/Users/妖梦/Desktop/TsubakiApi/Api/voice/atri"  # 输出文件的路径 例如 D:/1 不带后缀
  Tacotron: "D:/AtriVoice/Tacotron2Program/inference"  # Tacotron2的路径
  NoisePath: "D:/AtriVoice/Tacotron2Program/inference/denoise" # 降噪文件名

# 柚子社语音合成
yuzu:
  ModulePath: "D:/YuzuVoice/Data/243_epochs.pth" # 柚子社模型的绝对路径
  Config: "D:/YuzuVoice/Data/config.json" # 柚子社设置相关路径
  Output: "D:/YuzuVoice/Data/voice" # 输出路径
  Vits: "D:/YuzuVoice/MoeGoe/MoeGoe.exe" # VITS执行程序路径


