# 二次元人物声音合成相关设置

# 亚托莉
atri:
  ModulePath: ""  # 亚托莉模型的绝对路径
  OutPut: ""  # 输出文件的路径 例如 D:/1 不带后缀
  Tacotron: ""  # Tacotron2的路径
  NoisePath: "" # 降噪文件名

# 柚子社语音合成
yuzu:
  ModulePath: "" # 柚子社模型的绝对路径
  Config: "" # 柚子社设置相关路径
  Output: "" # 输出路径
  Vits: "" # VITS执行程序路径



