# 二次元人物声音合成相关设置

# 亚托莉
atri:
  ModulePath: ""  # 亚托莉模型的绝对路径
  OutPut: ""  # 输出文件的路径 例如 D:/1 不带后缀
  Tacotron: ""  # Tacotron2的路径
  NoisePath: "" # 降噪文件名

# 柚子社语音合成 所有路径名不允许非英文字符
yuzu:
  ModulePath: "" # 柚子社模型的绝对路径 带文件名
  Config: "" # 柚子社设置相关路径 带文件名
  Output: "" # 输出路径 不带文件名
  GoeMoePythonPath: "" # VGoeMoePython项目文件夹路径
  StringFile: "" # 缓存输出文件夹路径 不带文件名
  MaxConcurrent: 5 # 最大并发数



